### ISSUE TITLE
Usage without {{block-name}}?

### ISSUE THREAD

**Issue by jembezmamy** [retailnext/ember-bem-helpers#4]
Hey! Thanks for great addon, it's exactly what I was looking for. :)

I wonder if there is a way to use `{{bem}}` helper without `{{block-name}}`? I'd like to use it for some globally defined block names, e.g. layout parts ("column column--size-4"):

```htmlbars
{{block-name "my-component"}}

<div class="{{bem loaded=this.isLoaded}} {{bem "column" size=4}}">
  ... some content
</div>
```

This is what I get:

```html
<div class="my-component my-component--loaded my-component__column my-component__column--size-4">
  ... some content
</div>
```

What I'd like to get:

```html
<div class="my-component my-component--loaded column column--size-4">
  ... some content
</div>
```

I see that it collides with the default syntax - there is no way to tell if "column" is an Element or Block. So maybe we could add a new helper (`{{g-bem "column" size=4}}` like _global bem_) or allow passing empty Block name (`{{bem "" "column" size=4}}`)?

**Comment by andreyfel** [comment]
Hi @jembezmamy!

You can achieve what you want by using the `bem` helper in 2 different contexts:

You define my-component.hbs and specify `...attributes` on the root div:
```hbs
{{block-name "my-component"}}

<div class={{bem loaded=this.isLoaded}} ...attributes>
  ... some content
</div>
```

And use the MyComponent in the Column component like this:
```hbs
{{block-name "column"}}

<MyComponent class={{bem size=4}}>
  ... some content
</MyComponent>
```

Will it work for you?

**Comment by jembezmamy** [comment]
Thanks @andreyfel for a prompt answer. :)

Well, it may work in some cases and in some other it may not. For example I have globally defined button classes like: "primary-button primary-button--color-red". I use them inside my components and it would be a bit cumbersome to create a separate component for each button.

Actually I solved that in my project by just creating `g-bem` helper that simply extends `bem` helper. It doesn't get transformed by the AST plugin and that way I can use any block name regardless of the current context. :)

So for me the issue is solved. Maybe we could close this discussion until someone else brings it up again.

**Comment by andreyfel** [comment]
I think ideologically it is better to extract the PrimaryButton component and have these styles defined in the component styles file. You will be able to manage the modifiers by passing arguments to the component: `<PrimaryButton colorRed={{true}}>` and encapsulate the styling part within the component itself. 
```hbs
{{block-name "primary-button"}}

<button class={{bem color-red=@colorRed}}>
```
This is how we manage such things in our applications.
